/**
 * i18n keys — generated by Maven code generator (Task 2.8)
 *
 * Currently a placeholder with the minimal set of keys.
 * Run `mvn generate-i18n-keys` to regenerate from backend message bundles.
 */
export const i18nKeys = [
  'deviceNotFound',
  'userEmailDuplicate',
  'assignmentNotApproved',
  'rateLimitExceeded',
] as const

export type MessageKey = (typeof i18nKeys)[number]

export const defaultMessages: Record<MessageKey, string> = {
  deviceNotFound: 'Eszköz nem található',
  userEmailDuplicate: 'Ez az email cím már használatban van',
  assignmentNotApproved: 'A hozzárendelés még nincs jóváhagyva',
  rateLimitExceeded: 'Túl sok próbálkozás, kérjük várjon',
}